// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zad7JakubKazimierski.Models;

namespace Zad7JakubKazimierski.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20200120132429_Zad7JakubKazimierski.Models.VehicleContext")]
    partial class Zad7JakubKazimierskiModelsVehicleContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zad7JakubKazimierski.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarPrice")
                        .HasColumnType("int");

                    b.Property<string>("CarProducer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DateOfProduction")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Zad7JakubKazimierski.Models.MotorBike", b =>
                {
                    b.Property<int>("MBikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DateOfProduction")
                        .HasColumnType("int");

                    b.Property<string>("MBikeModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MBikePrice")
                        .HasColumnType("int");

                    b.Property<string>("MBikeProducer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MBikeId");

                    b.ToTable("MBikes");
                });
#pragma warning restore 612, 618
        }
    }
}
